language: generic

sudo: required

services:
  - docker

scripts:
  - docker build -t pxinghao/pytorch-serve-docker -f Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pxinghao/pytorch-serve-docker

